### PR TITLE
add SVG.py

### LINKED ISSUE #22: Request - SVG image rendering
Would you be able to design a way so that a full board can be rendered in svg? WIkipedia uses this feature for a lot of its chess articles.

Examples for chess:

Python-Chess: https://python-chess.readthedocs.io/en/latest/svg.html 

Web-boardimage rendering: https://github.com/niklasf/web-boardimage

### PR DESCRIPTION
**Pull request by yuiseki**
# Issue
- fix #22 

# Content
- Added `./shogi/SVG.py`.
- Updated `./shogi/__init__.py` to append `board.svg()` method.
- Updated `README.rst` to introduce `board.svg()` method.

# How To Check
- I cant understand how to write and run test in this project.
- So I've checked my code by python interpreter.
- `$ python`
- `>>> import shogi`
- `>>> board = shogi.Board()`
- `>>> board.svg()` should output SVG text.

# Others
- Base SVG string is published under Creative Commons BY-SA License, Is it safe to merge?
- If there are coding rules in this project, let me know so I can follow them.

### CODE REVIEW

**Comment by gunyarakun** [comment]
@yuiseki 
I generate a SVG file like following, but the image only contains a shogi board, not komas.
I checked with Firefox and Adobe Illustrator.
Could you check that?



```python
import shogi
board = shogi.Board()
print(board.svg())
```

**Comment by DerAndereJohannes** [comment]
I pulled yuiseki's branch and didn't have the same problem as you (pieces were loading! - not all though). I forked the project and managed to get it to work
## Default Board (as in your example)
Default Board

## SFEN ('4+R3l/1r1+P2gk1/3p1p1s1/2pg3pp/1p4p2/SP4PPP/2NP1PKS1/2G2+n3/8L w B2N2L3Pbgsp 10')
custom sfen

I can open a new pull request if you like to see!

**Comment by gunyarakun** [comment]
@DerAndereJohannes 
I wonder if you could make a new pull request, thank you!

**Comment by yuiseki** [comment]
Looks Nice! Sorry for my half-baked contribution

**Comment by DerAndereJohannes** [comment]
> Looks Nice! Sorry for my half-baked contribution

I did not do much to your code! You set it up very nicely! 😁👍 You can check it out in the other pull request!

**Comment by gunyarakun** [comment]
Close this pull request because of #36 .

**Pull request closed without merging**
